package com.miqt.vip.bean;

public class Constant {

    public static final String parcog = "[\n" +
            "        {\n" +
            "            \"name\":\"原地址-（提示：本软件免费无广告,不要花钱购买）\",\n" +
            "            \"url\":\"\"\n" +
            "        },\n" +
            "        {\n" +
            "            \"name\":\"万能接口5(腾讯好使)\",\n" +
            "            \"url\":\"http://jx.vgoodapi.com/jx.php?url=\"\n" +
            "        },\n" +
            "        {\n" +
            "            \"name\":\"无名小站\",\n" +
            "            \"url\":\"http://www.82190555.com/index/qqvod.php?url=\"\n" +
            "        },\n" +
            "        {\n" +
            "            \"name\":\"超清接口2\",\n" +
            "            \"url\":\"http://jiexi.92fz.cn/player/vip.php?url=\"\n" +
            "        },\n" +
            "        {\n" +
            "            \"name\":\"线路五\",\n" +
            "            \"url\":\"http://aikan-tv.com/?url=\"\n" +
            "        },\n" +
            "        {\n" +
            "            \"name\":\"百域阁视频\",\n" +
            "            \"url\":\"http://api.baiyug.cn/vip/index.php?url=\"\n" +
            "        },\n" +
            "        {\n" +
            "            \"name\":\"表哥解析\",\n" +
            "            \"url\":\"http://jx.biaoge.tv/index.php?url=\"\n" +
            "        },\n" +
            "        {\n" +
            "            \"name\":\"5月-4\",\n" +
            "            \"url\":\"http://beaacc.com/api.php?url=\"\n" +
            "        },\n" +
            "        {\n" +
            "            \"name\":\"4.21-4\",\n" +
            "            \"url\":\"http://www.82190555.com/index.php?url=\"\n" +
            "        },\n" +
            "        {\n" +
            "            \"name\":\"4.21-6\",\n" +
            "            \"url\":\"http://www.85105052.com/admin.php?url=\"\n" +
            "        },\n" +
            "        {\n" +
            "            \"name\":\"5月-19\",\n" +
            "            \"url\":\"http://yun.baiyug.cn/vip/?url=\"\n" +
            "        },\n" +
            "        {\n" +
            "            \"name\":\"5月-21\",\n" +
            "            \"url\":\"http://jiexi.071811.cc/jx2.php?url=\"\n" +
            "        },\n" +
            "        {\n" +
            "            \"name\":\"5月-23\",\n" +
            "            \"url\":\"http://api.baiyug.cn/vip/index.php?url=\"\n" +
            "        },\n" +
            "        {\n" +
            "            \"name\":\"9月-2\",\n" +
            "            \"url\":\"http://jqaaa.com/jx.php?url=\"\n" +
            "        },\n" +
            "        {\n" +
            "            \"name\":\"4.21-3-慢\",\n" +
            "            \"url\":\"https://yooomm.com/index.php?url=\"\n" +
            "        },\n" +
            "        {\n" +
            "            \"name\":\"5月-7\",\n" +
            "            \"url\":\"http://www.aktv.men/?url=\"\n" +
            "        },\n" +
            "        {\n" +
            "            \"name\":\"5月-24\",\n" +
            "            \"url\":\"http://www.82190555.com/index/qqvod.php?url=\"\n" +
            "        },\n" +
            "        {\n" +
            "            \"name\":\"1\",\n" +
            "            \"url\":\"http://17kyun.com/api.php?url=\"\n" +
            "        },\n" +
            "        {\n" +
            "            \"name\":\"8\",\n" +
            "            \"url\":\"http://tv.x-99.cn/api/wnapi.php?id=\"\n" +
            "        },\n" +
            "        {\n" +
            "            \"name\":\"品优解析-可播但广告\",\n" +
            "            \"url\":\"http://api.pucms.com/xnflv/?url=\"\n" +
            "        },\n" +
            "        {\n" +
            "            \"name\":\"5月-1\",\n" +
            "            \"url\":\"http://www.82190555.com/index/qqvod.php?url=\"\n" +
            "        },\n" +
            "        {\n" +
            "            \"name\":\"5月-2\",\n" +
            "            \"url\":\"http://jiexi.92fz.cn/player/vip.php?url=\"\n" +
            "        },\n" +
            "        {\n" +
            "            \"name\":\"5月-3\",\n" +
            "            \"url\":\"http://api.wlzhan.com/sudu/?url=\"\n" +
            "        },\n" +
            "        {\n" +
            "            \"name\":\"5月-22\",\n" +
            "            \"url\":\"http://www.82190555.com/index/qqvod.php?url=\"\n" +
            "        },\n" +
            "        {\n" +
            "            \"name\":\"高端解析\",\n" +
            "            \"url\":\"http://jx.vgoodapi.com/jx.php?url=\"\n" +
            "        },\n" +
            "        {\n" +
            "            \"name\":\"腾讯可用，线路三(云解析)\",\n" +
            "            \"url\":\"http://jiexi.92fz.cn/player/vip.php?url=\"\n" +
            "        },\n" +
            "        {\n" +
            "            \"name\":\"腾讯可用，金桥解析\",\n" +
            "            \"url\":\"http://jqaaa.com/jx.php?url=\"\n" +
            "        },\n" +
            "        {\n" +
            "            \"name\":\"线路四\",\n" +
            "            \"url\":\"http://api.nepian.com/ckparse/?url=\"\n" +
            "        },\n" +
            "        {\n" +
            "            \"name\":\"速度牛\",\n" +
            "            \"url\":\"http://api.wlzhan.com/sudu/?url=\"\n" +
            "        },\n" +
            "        {\n" +
            "            \"name\":\"万能接口6\",\n" +
            "            \"url\":\"http://wwwhe1.177kdy.cn/4.php?pass=1&url=\"\n" +
            "        },\n" +
            "        {\n" +
            "            \"name\":\"4.21-5\",\n" +
            "            \"url\":\"http://jiexi.92fz.cn/player/vip.php?url=\"\n" +
            "        },\n" +
            "        {\n" +
            "            \"name\":\"万能接口3---\",\n" +
            "            \"url\":\"http://vip.jlsprh.com/index.php?url=\"\n" +
            "        },\n" +
            "        {\n" +
            "            \"name\":\"6\",\n" +
            "            \"url\":\"http://014670.cn/jx/ty.php?url=\"\n" +
            "        },\n" +
            "        {\n" +
            "            \"name\":\"花园影视（可能无效）\",\n" +
            "            \"url\":\"http://j.zz22x.com/jx/?url=\"\n" +
            "        },\n" +
            "        {\n" +
            "            \"name\":\"9月-1\",\n" +
            "            \"url\":\"http://api.ledboke.com/?url=\"\n" +
            "        },\n" +
            "        {\n" +
            "            \"name\":\"10\",\n" +
            "            \"url\":\"http://7cyd.com/vip/?url=\"\n" +
            "        },\n" +
            "        {\n" +
            "            \"name\":\"5月-25\",\n" +
            "            \"url\":\"http://2gty.com/apiurl/yun.php?url=\"\n" +
            "        },\n" +
            "        {\n" +
            "            \"name\":\"5月-26\",\n" +
            "            \"url\":\"http://v.2gty.com/apiurl/yun.php?url=\"\n" +
            "        },\n" +
            "        {\n" +
            "            \"name\":\"5月-14-以下不可播\",\n" +
            "            \"url\":\"http://api.xyingyu.com/?url=\"\n" +
            "        },\n" +
            "        {\n" +
            "            \"name\":\"5月-15-XX\",\n" +
            "            \"url\":\"http://api.greatchina56.com/?url=\"\n" +
            "        },\n" +
            "        {\n" +
            "            \"name\":\"5月-16\",\n" +
            "            \"url\":\"http://api.baiyug.vip/index.php?url=\"\n" +
            "        },\n" +
            "        {\n" +
            "            \"name\":\"5月-17\",\n" +
            "            \"url\":\"http://api.visaok.net/?url=\"\n" +
            "        },\n" +
            "        {\n" +
            "            \"name\":\"5月-18\",\n" +
            "            \"url\":\"http://jx.618g.com/?url=\"\n" +
            "        },\n" +
            "        {\n" +
            "            \"name\":\"5月-20\",\n" +
            "            \"url\":\"hhttp://api.baiyug.cn/vip/?url=\"\n" +
            "        },\n" +
            "        {\n" +
            "            \"name\":\"花园影视1\",\n" +
            "            \"url\":\"http://j.88gc.net/jx/?url=\"\n" +
            "        },\n" +
            "        {\n" +
            "            \"name\":\"5月-6\",\n" +
            "            \"url\":\"http://api.lvcha2017.cn/?url=\"\n" +
            "        },\n" +
            "        {\n" +
            "            \"name\":\"爱跟影院\",\n" +
            "            \"url\":\"http://2gty.com/apiurl/yun.php?url=\"\n" +
            "        },\n" +
            "        {\n" +
            "            \"name\":\"六六视频\",\n" +
            "            \"url\":\"http://qtv.soshane.com/ko.php?url=\"\n" +
            "        },\n" +
            "        {\n" +
            "            \"name\":\"超清接口1_0\",\n" +
            "            \"url\":\"http://www.52jiexi.com/tong.php?url=\"\n" +
            "        },\n" +
            "        {\n" +
            "            \"name\":\"超清接口1_1\",\n" +
            "            \"url\":\"http://www.52jiexi.com/yun.php?url=\"\n" +
            "        },\n" +
            "        {\n" +
            "            \"name\":\"线路一(乐乐视频解析)\",\n" +
            "            \"url\":\"http://www.662820.com/xnflv/index.php?url=\"\n" +
            "        },\n" +
            "        {\n" +
            "            \"name\":\"1717ty\",\n" +
            "            \"url\":\"http://1717ty.duapp.com/jx/ty.php?url=\"\n" +
            "        },\n" +
            "        {\n" +
            "            \"name\":\"万能接口4\",\n" +
            "            \"url\":\"https://api.daidaitv.com/index/?url=\"\n" +
            "        },\n" +
            "        {\n" +
            "            \"name\":\"5月-5\",\n" +
            "            \"url\":\"http://www.ckplayer.tv/kuku/?url=\"\n" +
            "        },\n" +
            "        {\n" +
            "            \"name\":\"5月-13\",\n" +
            "            \"url\":\"http://jx.reclose.cn/jx.php/?url=\"\n" +
            "        },\n" +
            "        {\n" +
            "            \"name\":\"9月-4\",\n" +
            "            \"url\":\"http://jx.du2.cc/?url=\"\n" +
            "        },\n" +
            "        {\n" +
            "            \"name\":\"4.21-2\",\n" +
            "            \"url\":\"http://qtv.soshane.com/ko.php?url=\"\n" +
            "        },\n" +
            "        {\n" +
            "            \"name\":\"9月-3\",\n" +
            "            \"url\":\"http://jx.du2.cc/jx6.php?url=\"\n" +
            "        },\n" +
            "        {\n" +
            "            \"name\":\"5月-8\",\n" +
            "            \"url\":\"http://api.visaok.net/?url=\"\n" +
            "        },\n" +
            "        {\n" +
            "            \"name\":\"5月-9\",\n" +
            "            \"url\":\"http://api.xyingyu.com/?url=\"\n" +
            "        },\n" +
            "        {\n" +
            "            \"name\":\"5月-10\",\n" +
            "            \"url\":\"http://api.greatchina56.com/?url=\"\n" +
            "        },\n" +
            "        {\n" +
            "            \"name\":\"5月-11\",\n" +
            "            \"url\":\"http://jx.618g.com/?url=\"\n" +
            "        },\n" +
            "        {\n" +
            "            \"name\":\"5月-12\",\n" +
            "            \"url\":\"http://api.baiyug.vip/index.php?url=\"\n" +
            "        }\n" +
            "    ]";


    public static final String PARS_URL = "https://iodefog.github.io/text/mviplistmm.json";
    public static final String ACTION_UTL = "https://iodefog.github.io/text/mviplistmm.json";
    public static final String ACTION_CONTENT = "[\n" +
            "        {\n" +
            "            \"name\":\"爱奇艺\",\n" +
            "            \"url\":\"http://www.iqiyi.com/\"\n" +
            "        },\n" +
            "        {\n" +
            "            \"name\":\"腾讯视频\",\n" +
            "            \"url\":\"https://v.qq.com/\"\n" +
            "        },\n" +
            "        {\n" +
            "            \"name\":\"芒果\",\n" +
            "            \"url\":\"https://www.mgtv.com/\"\n" +
            "        },\n" +
            "        {\n" +
            "            \"name\":\"优酷\",\n" +
            "            \"url\":\"https://www.youku.com/\"\n" +
            "        },\n" +
            "        {\n" +
            "            \"name\":\"搜狐视频\",\n" +
            "            \"url\":\"https://tv.sohu.com/\"\n" +
            "        },\n" +
            "        {\n" +
            "            \"name\":\"乐视视频\",\n" +
            "            \"url\":\"https://www.le.com/\"\n" +
            "        },\n" +
            "        {\n" +
            "            \"name\":\"电影天堂\",\n" +
            "            \"url\":\"http://www.btbtdy.net/\"\n" +
            "        },\n" +
            "        {\n" +
            "            \"name\":\"52影院\",\n" +
            "            \"url\":\"http://www.52xsba.com/\"\n" +
            "        },\n" +
            "        {\n" +
            "            \"name\":\"4080新视觉影院\",\n" +
            "            \"url\":\"http://www.yy4080.com/\"\n" +
            "        }\n" +
            "    ]";
}
